### ISSUE TITLE
Error injecting constructor, java.lang.RuntimeException: Base app is not initialized

### ISSUE THREAD

**Issue by ecrazor1911** [axelor/axelor-business-suite#1521]
# Console output
```
2018-03-17 13:35:27.441 DEBUG 82 --- [ost-startStop-1] com.axelor.db.JpaModule                  : Configuring database...
2018-03-17 13:35:28.895  INFO 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configuring app modules...
2018-03-17 13:35:28.895 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.base.module.AdminModule
2018-03-17 13:35:28.902 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.message.module.MessageModule
2018-03-17 13:35:28.916 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.base.module.BaseModule
2018-03-17 13:35:28.978 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.account.module.AccountModule
2018-03-17 13:35:29.067 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.bankpayment.module.BankPaymentModule
2018-03-17 13:35:29.106 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.crm.module.CrmModule
2018-03-17 13:35:29.121 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.sale.module.SaleModule
2018-03-17 13:35:29.160 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.project.module.ProjectModule
2018-03-17 13:35:29.172 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.hr.module.HumanResourceModule
2018-03-17 13:35:29.220 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.purchase.module.PurchaseModule
2018-03-17 13:35:29.230 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.stock.module.StockModule
2018-03-17 13:35:29.262 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.supplychain.module.SupplychainModule
2018-03-17 13:35:29.321 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.businessproject.module.BusinessProjectModule
2018-03-17 13:35:29.333 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.production.module.ProductionModule
2018-03-17 13:35:29.369 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.businessproduction.module.BusinessProductionModule
2018-03-17 13:35:29.385 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.contract.module.ContractModule
2018-03-17 13:35:29.392 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.fleet.module.FleetModule
2018-03-17 13:35:29.490 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.helpdesk.module.HelpdeskModule
2018-03-17 13:35:29.498 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.studio.module.StudioModule
2018-03-17 13:35:29.511 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.marketing.module.MarketingModule
2018-03-17 13:35:29.516 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.prestashop.module.PrestaShopModule
2018-03-17 13:35:29.554 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.quality.module.QualityModule
2018-03-17 13:35:29.560 DEBUG 82 --- [ost-startStop-1] com.axelor.app.AppModule                 : Configure module: com.axelor.apps.talent.module.TalentModule
2018-03-17 13:35:35.032 DEBUG 82 --- [pool-2-thread-1] com.axelor.db.JpaScanner                 : Searching for entity classes...
2018-03-17 13:35:35.055 DEBUG 82 --- [pool-2-thread-2] com.axelor.db.JpaScanner                 : Searching for repository classes...
2018-03-17 13:35:35.098 DEBUG 82 --- [pool-2-thread-3] com.axelor.db.JpaScanner                 : Searching for value enum classes...
2018-03-17 13:35:35.986 DEBUG 82 --- [pool-2-thread-3] com.axelor.db.JpaScanner                 : Value enum classes found: 1
2018-03-17 13:35:36.607 DEBUG 82 --- [pool-2-thread-2] com.axelor.db.JpaScanner                 : Repository classes found: 540
2018-03-17 13:35:49.681 DEBUG 82 --- [pool-2-thread-1] com.axelor.db.JpaScanner                 : Entity classes found: 459
2018-03-17 13:36:07.528 UTC [124] ERROR:  relation "bankpayment_bank_statement_line_operation_interbank_code_line_i" already exists
2018-03-17 13:36:07.528 UTC [124] STATEMENT:  create index bankpayment_bank_statement_line_operation_interbank_code_line_IDX on bankpayment_bank_statement_line (operation_interbank_code_line)
2018-03-17 13:36:07.567 UTC [124] ERROR:  relation "bankpayment_bank_statement_line_afb120bankpayment_bank_statemen" already exists
2018-03-17 13:36:07.567 UTC [124] STATEMENT:  create index bankpayment_bank_statement_line_afb120bankpayment_bank_statement_line_currency_IDX on bankpayment_bank_statement_line_afb120 (currency)
2018-03-17 13:36:07.568 UTC [124] ERROR:  relation "bankpayment_bank_statement_line_afb120bankpayment_bank_statemen" already exists
2018-03-17 13:36:07.568 UTC [124] STATEMENT:  create index bankpayment_bank_statement_line_afb120bankpayment_bank_statement_line_bank_details_IDX on bankpayment_bank_statement_line_afb120 (bank_details)
2018-03-17 13:36:07.569 UTC [124] ERROR:  relation "bankpayment_bank_statement_line_afb120bankpayment_bank_statemen" already exists
2018-03-17 13:36:07.569 UTC [124] STATEMENT:  create index bankpayment_bank_statement_line_afb120bankpayment_bank_statement_line_operation_interbank_code_line_IDX on bankpayment_bank_statement_line_afb120 (operation_interbank_code_line)
2018-03-17 13:36:07.569 UTC [124] ERROR:  relation "bankpayment_bank_statement_line_afb120bankpayment_bank_statemen" already exists
2018-03-17 13:36:07.569 UTC [124] STATEMENT:  create index bankpayment_bank_statement_line_afb120bankpayment_bank_statement_line_reject_interbank_code_line_IDX on bankpayment_bank_statement_line_afb120 (reject_interbank_code_line)
2018-03-17 13:36:07.570 UTC [124] ERROR:  relation "bankpayment_bank_statement_line_afb120bankpayment_bank_statemen" already exists
2018-03-17 13:36:07.570 UTC [124] STATEMENT:  create index bankpayment_bank_statement_line_afb120bankpayment_bank_statement_line_bank_statement_IDX on bankpayment_bank_statement_line_afb120 (bank_statement)
2018-03-17 13:36:14.356 UTC [124] ERROR:  relation "production_configurator_prod_process_line_configurator_prod_pro" already exists
2018-03-17 13:36:14.356 UTC [124] STATEMENT:  create index production_configurator_prod_process_line_configurator_prod_process_IDX on production_configurator_prod_process_line (configurator_prod_process)
2018-03-17 13:36:16.003 UTC [124] ERROR:  relation "stock_freight_carrier_customer_account_number_carrier_partner_i" already exists
2018-03-17 13:36:16.003 UTC [124] STATEMENT:  create index stock_freight_carrier_customer_account_number_carrier_partner_IDX on stock_freight_carrier_customer_account_number (carrier_partner)
2018-03-17 13:36:21.870 UTC [124] ERROR:  foreign key constraint "fk_cr7pkyx8viga5nd0p1i20r762" cannot be implemented
2018-03-17 13:36:21.870 UTC [124] DETAIL:  Key columns "default_partner_language" and "id" are of incompatible types: character varying and bigint.
2018-03-17 13:36:21.870 UTC [124] STATEMENT:  alter table base_app_base add constraint FK_cr7pkyx8viga5nd0p1i20r762 foreign key (default_partner_language) references base_language
2018-03-17 13:36:31.793  INFO 82 --- [ost-startStop-1] com.axelor.web.AppInitializer            : Initializing...
2018-03-17 13:36:33.619  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-core...
2018-03-17 13:36:33.621  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-web...
2018-03-17 13:36:33.622  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-exception...
2018-03-17 13:36:33.624  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-admin...
2018-03-17 13:36:33.625  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-tool...
2018-03-17 13:36:33.626  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-message...
2018-03-17 13:36:33.627  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-base...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-account...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-bank-payment...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-crm...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-sale...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-project...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-human-resource...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-purchase...
2018-03-17 13:36:33.632  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-stock...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-supplychain...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-business-project...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-production...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-business-production...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-cash-management...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-client-portal...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-contract...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-fleet...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-helpdesk...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-studio...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-marketing...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-prestashop...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-quality...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-supplier-management...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-talent...
2018-03-17 13:36:33.633  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-teamsapp...
2018-03-17 13:36:33.634  INFO 82 --- [ost-startStop-1] com.axelor.meta.loader.ModuleManager     : Loading package axelor-erp...
2018-03-17 13:36:34.069 DEBUG 82 --- [ost-startStop-1] com.axelor.meta.loader.ViewLoader        : Loading view: prestashop-order-status-cache-entry-grid
2018-03-17 13:36:35.681 DEBUG 82 --- [ost-startStop-1] com.axelor.meta.loader.ViewLoader        : Loading view: prestashop-order-status-cache-entry-form
2018-03-17 13:36:35.696 DEBUG 82 --- [ost-startStop-1] com.axelor.meta.loader.ViewLoader        : Creating default views: /tmp/axelor/generated/views/PrestashopOrderStatusCacheEntry.xml
2018-03-17 13:36:35.873  INFO 82 --- [ost-startStop-1] com.axelor.web.AppInitializer            : Ready to serve...

Running at http://localhost:8080/axelor-erp

2018-03-17 13:37:13.336 DEBUG 82 --- [nio-8080-exec-2] com.axelor.rpc.Resource                  : Searching 'com.axelor.meta.db.MetaMenu' with {_domain=self.user = :__user__ and self.link is not null, _domainContext={}}
2018-03-17 13:37:13.431 DEBUG 82 --- [nio-8080-exec-2] com.axelor.rpc.Resource                  : JPQL: SELECT  new List(self.id, self.version, self.id, self.name, self.title, self.link) FROM MetaMenu self LEFT JOIN self.user _user WHERE ((_user = :__user__ and self.link is not null) AND (self.archived is null OR self.archived = false)) ORDER BY self.priority DESC, self.id DESC
2018-03-17 13:37:13.480 DEBUG 82 --- [nio-8080-exec-2] com.axelor.rpc.Resource                  : Records found: 0
2018-03-17 13:37:13.808 DEBUG 82 --- [nio-8080-exec-6] c.a.meta.schema.actions.ActionGroup      : action: account.bank.order.awaiting.for.signature
2018-03-17 13:37:13.918 ERROR 82 --- [nio-8080-exec-6] o.h.engine.jdbc.spi.SqlExceptionHelper   : Bad value for type long : en
2018-03-17 13:37:13.944 ERROR 82 --- [nio-8080-exec-6] com.axelor.script.CompositeScriptHelper  : Script error: __config__.app.isApp('base') && __config__.app.getApp('base').getEnterpriseCommunication()
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: Base app is not initialized
  at com.axelor.apps.production.service.app.AppProductionServiceImpl.<init>(AppProductionServiceImpl.java:43)
  at com.axelor.apps.production.service.app.AppProductionServiceImpl.class(AppProductionServiceImpl.java:43)
  while locating com.axelor.apps.production.service.app.AppProductionServiceImpl
  while locating com.axelor.apps.base.service.app.AppBaseServiceImpl
  while locating com.axelor.apps.base.service.app.AppServiceImpl
  while locating com.axelor.apps.base.service.app.AppService

1 error
   at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
   at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
   at com.axelor.inject.Beans.get(Beans.java:63)
   at com.axelor.script.ScriptBindings$ConfigContext.get(ScriptBindings.java:264)
   at groovy.lang.MetaClassImpl$6.getProperty(MetaClassImpl.java:1895)
   at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
   at script1521293833826345474296.run(script1521293833826345474296.groovy:1)
   at com.axelor.script.GroovyScriptHelper.eval(GroovyScriptHelper.java:138)
   at com.axelor.script.CompositeScriptHelper.eval(CompositeScriptHelper.java:80)
   at com.axelor.script.AbstractScriptHelper.eval(AbstractScriptHelper.java:91)
   at com.axelor.script.AbstractScriptHelper.test(AbstractScriptHelper.java:52)
   at com.axelor.meta.service.MetaService.test(MetaService.java:137)
   at com.axelor.meta.service.MetaService.canShow(MetaService.java:115)
   at com.axelor.meta.service.MetaService.filter(MetaService.java:162)
   at com.axelor.meta.service.MetaService.getMenus(MetaService.java:378)
   at com.axelor.web.service.ActionService.all(ActionService.java:64)
   at com.axelor.web.service.ActionService$$EnhancerByGuice$$727a49e4.CGLIB$all$3(<generated>)
   at com.axelor.web.service.ActionService$$EnhancerByGuice$$727a49e4$$FastClassByGuice$$ed29834f.invoke(<generated>)
   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
   at com.axelor.rpc.ResponseInterceptor.invoke(ResponseInterceptor.java:65)
   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
   at com.axelor.web.service.ActionService$$EnhancerByGuice$$727a49e4.all(<generated>)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
   at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
   at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
   at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
   at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
   at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
   at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
   at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
   at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
   at com.axelor.db.tenants.AbstractTenantFilter.doFilter(AbstractTenantFilter.java:73)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
   at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
   at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
   at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
   at com.axelor.auth.AuthFilter.doFilterInternal(AuthFilter.java:81)
   at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
   at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
   at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
   at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
   at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
   at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
   at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
   at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
   at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
   at com.axelor.app.internal.AppFilter.doFilter(AppFilter.java:94)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:91)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
   at com.axelor.db.tenants.AbstractTenantFilter.doFilter(AbstractTenantFilter.java:73)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
   at com.axelor.web.servlet.CorsFilter.doFilter(CorsFilter.java:136)
   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Base app is not initialized
   at com.axelor.apps.base.service.app.AppBaseServiceImpl.<init>(AppBaseServiceImpl.java:55)
   at com.axelor.apps.production.service.app.AppProductionServiceImpl.<init>(AppProductionServiceImpl.java:43)
   at com.axelor.apps.production.service.app.AppProductionServiceImpl$$EnhancerByGuice$$b6bc0b6.<init>(<generated>)
   at com.axelor.apps.production.service.app.AppProductionServiceImpl$$EnhancerByGuice$$b6bc0b6$$FastClassByGuice$$7033247.newInstance(<generated>)
   at com.google.inject.internal.ProxyFactory$ProxyConstructor.newInstance(ProxyFactory.java:265)
   at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
   at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
   at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:95)
   at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
   at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
   at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
   at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:92)
   at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
   at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
   at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
   at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
   at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
   at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
   at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
   at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
   at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
   at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
   at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
   at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
   ... 84 common frames omitted
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute query
   at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147)
   at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
   at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1423)
   at org.hibernate.query.Query.getResultList(Query.java:146)
   at com.axelor.db.Query.fetch(Query.java:339)
   at com.axelor.db.Query.fetch(Query.java:326)
   at com.axelor.db.Query.fetchOne(Query.java:365)
   at com.axelor.apps.base.service.app.AppBaseServiceImpl.<init>(AppBaseServiceImpl.java:54)
   ... 107 common frames omitted
Caused by: org.hibernate.exception.DataException: could not execute query
   at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:118)
   at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
   at org.hibernate.loader.Loader.doList(Loader.java:2618)
   at org.hibernate.loader.Loader.doList(Loader.java:2598)
   at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2430)
   at org.hibernate.loader.Loader.list(Loader.java:2425)
   at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:379)
   at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
   at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1488)
   at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445)
   at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
   ... 112 common frames omitted
Caused by: org.postgresql.util.PSQLException: Bad value for type long : en
   at org.postgresql.jdbc.PgResultSet.toLong(PgResultSet.java:2859)
   at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2113)
   at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2505)
   at com.zaxxer.hikari.pool.HikariProxyResultSet.getLong(HikariProxyResultSet.java)
   at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$2.doExtract(BigIntTypeDescriptor.java:63)
   at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
   at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:260)
   at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:256)
   at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:246)
   at org.hibernate.type.ManyToOneType.hydrate(ManyToOneType.java:179)
   at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2844)
   at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1741)
   at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1667)
   at org.hibernate.loader.Loader.getRow(Loader.java:1556)
   at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:740)
   at org.hibernate.loader.Loader.processResultSet(Loader.java:985)
   at org.hibernate.loader.Loader.doQuery(Loader.java:943)
   at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
   at org.hibernate.loader.Loader.doList(Loader.java:2615)
   ... 121 common frames omitted

```

**Comment by beuss** [comment]
Hi,
this is due to application.mode being set to `prod` instead of `dev`, this is actually an ADK issue and should have been fixed in e350425f0f4e2fd8d83a65ebba56f052b2d70b4e (https://github.com/axelor/axelor-development-kit/commit/e350425f0f4e2fd8d83a65ebba56f052b2d70b4e)

**Comment by gdu-axelor** [comment]
Not due to prod mode but due to recent changes on the field defaultPartnerLanguage on AppBase. See https://github.com/axelor/axelor-business-suite/commit/c5e385c9b2106e3165451befe79651fa29317a86  The string selection field has been replaced per a M2O to Language object in order to allow the user to add easily new partner language and translate the printing according the new language. You have to reset the database or run a SQL script to migrate data.

**Comment by ecrazor1911** [comment]
Hi,
@beuss I changed application.mode to `prod`, but doesn't solve this problem.
@gdu-axelor I see, thank you. How can I easily migrate existing data? 
Thank you.

**Comment by gdu-axelor** [comment]
To migrate existing data, you have to run SQL script like following for AppBase : 

> update base_language set code = lower(code);
> update base_app_base as AppBase set default_partner_language = (select Language.id from base_language as Language where Language.code = AppBase.default_partner_language); 
> alter table base_app_base alter column default_partner_language type bigint USING default_partner_language::bigint;

Also you have to migrate Partner and EbicsBank objects or set the value manually.
